INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (1,'Hello! How can I help you?','Question', null , 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (2,'Game is lagging','Answer',1, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (3,'Account hacked','Answer', 1, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (4,'Report some other Issue','Answer',1, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (5,'Did you restart the Game?','Question',2, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (6,'Yes, I restarted the Game','Answer',5, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (7,'No, I didn''t restart the Game','Answer',5, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (8,'Please try restarting the Game','Question',7, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (9,'Didn''t that fix the Issue?','Question',6, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (10,'Yes, It fixed the issue','Answer',9, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (11,'No, It didn''t fix the issue','Answer',9, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (12,'Did you restart the Device?','Question',11, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (13,'Yes, I restarted the Device','Answer',12, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (14,'No, I didn''t restart the Device','Answer',12, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (15,'Please try restarting the Device','Question',14, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (16,'Didn''t that fix the Issue?','Question',13, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (17,'Yes, It fixed the issue','Answer',16, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (18,'No, It didn''t fix the issue','Answer',16, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (19,'Please describe the issue below','Question',18, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (20,'Do you want to restore the account?','Question',3, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (21,'Yes, I want to restore the account','Answer',20, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (22,'No, I don''t want to restore the account','Answer',20, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (23,'How do you want to restore?','Question',21, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (24,'Full restore (Restores the account data with a new account)','Answer',23, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (25,'Partial restore(Restore only hacked platform)','Answer',23, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (26,'Please mention the new account details below','Question',24, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (27,'Please help up by providing the hacked platform details below','Question',25, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (28,'Please describe the issue below','Question',4, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (29,'Yes, It fixed the issue','Answer',8, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (30,'No, I have different issue','Answer',8, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (31,'Please describe the issue below','Question',30, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (32,'Yes, It fixed the issue','Answer',15, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (33,'No, I have different issue','Answer',15, 1);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (34,'Please describe the issue below','Question',33, 1);
 
 
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (35,'नमस्ते! मैं आपकी कैसे मदद कर सकता हूँ?','Question', null, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (36,'खेल पिछड़ रहा है','Answer',35, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (37,'अकाउंट हैक हो गया','Answer', 35, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (38,'किसी अन्य मुद्दे की रिपोर्ट करें','Answer',35, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (39,'क्या आपने गेम पुनः आरंभ किया?','Question',36, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (40,'हाँ, मैंने खेल पुनः प्रारंभ किया','Answer',39, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (41,'नहीं, मैंने गेम पुनः प्रारंभ नहीं किया है','Answer',39, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (42,'कृपया खेल को पुनः आरंभ करने का प्रयास करें','Question',41, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (43,'क्या इससे समस्या ठीक नहीं हुई?','Question',40, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (44,'हाँ, इससे समस्या ठीक हो गई','Answer',43, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (45,'नहीं, इससे समस्या ठीक नहीं हुई','Answer',43, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (46,'क्या आपने डिवाइस को पुनरारंभ किया?','Question',45, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (47,'हां, मैंने डिवाइस को पुनः प्रारंभ किया है','Answer',46, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (48,'नहीं, मैंने डिवाइस को पुनरारंभ नहीं किया','Answer',46, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (49,'कृपया डिवाइस को पुनः प्रारंभ करने का प्रयास करें','Question',48, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (50,'क्या इससे समस्या ठीक नहीं हुई?','Question',47, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (51,'हाँ, इससे समस्या ठीक हो गई','Answer',50, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (52,'नहीं, इससे समस्या ठीक नहीं हुई','Answer',50, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (53,'कृपया नीचे समस्या का वर्णन करें','Question',52, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (54,'क्या आप खाता पुनर्स्थापित करना चाहते हैं?','Question',37, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (55,'हाँ, मैं खाता पुनर्स्थापित करना चाहता हूँ','Answer',54, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (56,'नहीं, मैं खाता पुनर्स्थापित नहीं करना चाहता','Answer',54, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (57,'आप कैसे पुनर्स्थापित करना चाहते हैं?','Question',55, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (58,'पूर्ण पुनर्स्थापना (नए खाते के साथ खाता डेटा पुनर्स्थापित करता है)','Answer',57, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (59,'आंशिक पुनर्स्थापना (केवल हैक किए गए प्लेटफ़ॉर्म को पुनर्स्थापित करें)','Answer',57, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (60,'कृपया नीचे नए खाते का विवरण बताएं','Question',58, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (61,'कृपया नीचे हैक किए गए प्लेटफ़ॉर्म विवरण प्रदान करके सहायता करें','Question',59, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (62,'कृपया नीचे समस्या का वर्णन करें','Question',38, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (63,'हाँ, इससे समस्या ठीक हो गई','Answer',42, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (64,'नहीं, मेरा मुद्दा अलग है','Answer',42, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (65,'कृपया नीचे समस्या का वर्णन करें','Question',64, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (66,'हाँ, इससे समस्या ठीक हो गई','Answer',49, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (67,'नहीं, मेरा मुद्दा अलग है','Answer',49, 2);
INSERT INTO chat_content(id,content,content_type,parent_id, language_id) VALUES (68,'कृपया नीचे समस्या का वर्णन करें','Question',67, 2);

insert into users(first_name , last_name , preferred_language, platform, title) values('nethaji', 'm', ARRAY[1, 2, 3], ARRAY[1, 2, 3], ARRAY[1, 2, 3] );
insert into users(first_name , last_name , preferred_language, platform, title) values('muthu', 'm', ARRAY[3, 4, 5], ARRAY[1, 2, 3], ARRAY[1, 2, 3] );
insert into users(first_name , last_name , preferred_language, platform, title) values('john', 'm', ARRAY[6, 7, 8], ARRAY[6, 7, 8], ARRAY[6, 7, 8] );
	   
insert into PLAYER (ID ,FIRST_NAME ,LAST_NAME ,PLATFORM ,PREFERRED_LANGUAGE ,TITLE )values(2233344, 'john', 'cena', 1,1,1 );
insert into PLAYER (ID ,FIRST_NAME ,LAST_NAME ,PLATFORM ,PREFERRED_LANGUAGE ,TITLE )values(2233345, 'robert', 'roy', 6,6,6 );